- name: "Extract Zipped artifact to EC2"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "Install NodeJS"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install NPM"
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes

- name: "Install Packages"
  command:
    cmd: npm install

- name: "Start application"
  command:
    cmd: pm2 start npm -- start

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save